---
application:
    name: spring-boot-starter
    version: ${project.version}

info:
  app:
    encoding: "${project.build.sourceEncoding}"
    java:
      source: "${java.version}"
      target: "${java.version}"

management:
    server:
        port: 8081
    endpoints:
        enabled-by-default: true
        web:
            discovery:
                enabled: true
            exposure:
                include: health,ping,prometheus,livenessstate,readinessstate
            cors:
                allowed-origins: "http://localhost/"
                allowed-methods: "GET,POST"
        jmx:
            exposure:
                include: "*"
    info:
        git:
            mode: "full"