apiVersion: v1
kind: Service
metadata:
  name: {{ include "@project.artifactId@.fullname" . }}
  labels:
    {{- include "@project.artifactId@.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.management.port }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "@project.artifactId@.selectorLabels" . | nindent 4 }}
